package org.iptc.extra.core.cql;

public enum EXTRAOperators {
	AND, 
	OR,
	NOT,
	MINIMUM,
	DISTANCE,
	MINIMUM_OCCURRENCE,
	ORDER,
	SENTENCE,
	NOT_WITHIN_DISTANCE,
	PARAGRAPH,
	NOT_IN_PHRASE,
	NOT_IN_SENTENCE,
	NOT_IN_PARAGRAPH,
	ORDER_AND_DISTANCE,
	MAXIMUM_OCCURRENCE,
	FROM_START,
	FROM_END,
	MAXIMUM_SENTENCES,
	MAXIMUM_PARAGRAPHS,
	PARAGRAPH_POSITION
}
